export const API_REQUEST = "API_REQUEST";
// AUTH 
export const ACCOUNT_TYPE_OPT = "ACCOUNT_TYPE_OPT";
export const APPS_OPT = "APPS_OPT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const LOGOUT = "LOGOUT";
export const AUTH_PROFILE = "AUTH_PROFILE";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_USER = "AUTH_USER";
export const AUTH_GET_USER = "AUTH_GET_USER";
export const AUTH_STATUS = "AUTH_STATUS";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_ROLE = "AUTH_ROLE";
export const SOCKET_CLIENT = "SOCKET_CLIENT";
export const AUTH_DESTROY_SESSION = "AUTH_DESTROY_SESSION";
export const AUTHENTICATOR = "AUTHENTICATOR";
export const USER_CURRENT_SESSION = 'USER_CURRENT_SESSION';

export const DELETEALL_COOKIES = "DELETEALL_COOKIES";

export const ROLE_OPT = "ROLE_OPT";
export const ROLE_TAG_OPT = "ROLE_TAG_OPT";

export const VISITOBJ_OPTIONS = "VISITOBJ_OPTIONS";
export const AGEN_OPTIONS = "AGEN_OPTIONS";
export const AGEN_CREATE = "AGEN_CREATE";
export const AGEN_UPDATE = "AGEN_UPDATE";
export const AGEN_DELETE = "AGEN_DELETE";
export const AGEN_PROFILE = "AGEN_PROFILE";
export const AGEN_EXPORT = "AGEN_EXPORT";

export const RTL_TODISTRICT_OPTIONS = "RTL_TODISTRICT_OPTIONS";
export const RTL_TOVISIT_OPTIONS = "RTL_TOVISIT_OPTIONS";
export const RTL_HO = "RTL_HO";
export const RTL_TOTAX = "RTL_TOTAX";

export const SALES_OPTIONS = "SALES_OPTIONS";
export const SALES_VISIT = "SALES_VISIT";
export const SALES_TOVISITA = "SALES_TOVISITA"; // agen
export const SALES_TOVISITI = "SALES_TOVISITI"; // intimacy

export const TOCUST_OPTIONS = "TOCUST_OPTIONS";
export const TOAGEN_OPTIONS = "TOAGEN_OPTIONS";
export const VISITAGEN_OPTIONS = "VISITAGEN_OPTIONS";

export const VISIT_ACTION = "VISIT_ACTION";
export const ACTIVITY_SUBMIT = "ACTIVITY_SUBMIT";
export const ACTIVITY_SAVE = "ACTIVITY_SAVE";
export const ACTIVITY_SHOW = "ACTIVITY_SHOW";
export const ACTIVITY_DROP = "ACTIVITY_DROP";

export const TOCHKGRP_ALL = "TOCHKGRP_ALL";
export const TOCHKGRP_ALL_RESP = "TOCHKGRP_ALL_RESP";
export const TOCHKGRP_SHOW = "TOCHKGRP_SHOW";
export const CRYPT_ACTION = "CRYPT_ACTION";
export const RTL_GET_COND = "RTL_GET_COND";

export const DASH_VSAI = "DASH_VSAI";
export const DASH_VAM = "DASH_VAM";
export const DASH_DEV = "DASH_DEV";

export const RTL_EXPORT_REPORT = "RTL_EXPORT_REPORT";
export const RTL_ACPIC = "RTL_ACPIC"; // autocomplete pic
export const LIST_SCOPES = "LIST_SCOPES";

// USER
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const USER_SET_BEFORE_VERIFIED_CODE_EMAIL = "USER_SET_BEFORE_VERIFIED_CODE_EMAIL";
export const USER_SET_VERIFIED_CODE_EMAIL = "USER_SET_VERIFIED_CODE_EMAIL";
export const USER_SET_EMAIL = "USER_SET_EMAIL";
export const USER_GET_PROFILE = "USER_GET_PROFILE";
export const USER_SAVE_PROFILE = "USER_SAVE_PROFILE";
export const USER_CHECK_SCOPE = "USER_CHECK_SCOPE";
export const USER_GET_PHOTO = "USER_GET_PHOTO";
export const USER_DELETE_PHOTO = "USER_DELETE_PHOTO";
export const USER_GET_SESSION = "USER_GET_SESSION";
export const USER_UPDATE_SESSION = "USER_UPDATE_SESSION";

// AUTH
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

// FILTER GETLIST
export const FG_DBAGEN = "FG_DBAGEN";

// GALLERY
export const GALLERY_ITEMS = "GALLERY_ITEMS";
export const GALLERY_SHOW = " GALLERY_SHOW";
export const GALLERY_SHOW_ARR = "GALLERY_SHOW_ARR";

// LIBRARY TYPEOF

export const LIBRARY_DEL_CATEGORY = "LIBRARY_DEL_CATEGORY";
export const LIBRARY_CREATE_CATEGORY = "LIBRARY_CREATE_CATEGORY";
export const LIBRARY_GET_CATEGORY = "LIBRARY_GET_CATEGORY";
export const LIBRARY_GET_STATUSES = "LIBRARY_GET_STATUSES";
export const LIBRARY_GET_VISIBILITY = "LIBRARY_GET_VISIBILITY";

// LIBRARY GET DATA
export const LIBRARY_ARTICLES_ANALYZE = "LIBRARY_ARTICLES_ANALYZE";
export const LIBRARY_GET_ARTICLES = "LIBRARY_GET_ARTICLES";
export const LIBRARY_GET_ARTICLES_SINGLE = "LIBRARY_GET_ARTICLES_SINGLE";
export const LIBRARY_DELETE_ARTICLES = "LIBRARY_DELETE_ARTICLES";
export const LIBRARY_BOOKMARK_ARTICLES = "LIBRARY_BOOKMARK_ARTICLES";
export const LIBRARY_BOOKMARK_ARTICLES_DEL = "LIBRARY_BOOKMARK_ARTICLES_DEL";

// LIBRARY GET MY DOCUMENT

export const LIBRARY_GET_MY_DOC = "LIBRARY_GET_MY_DOC";
export const LIBRARY_CREATE_MY_DOC = "LIBRARY_CREATE_MY_DOC";
export const LIBRARY_UPDATE_MY_DOC = "LIBRARY_UPDATE_MY_DOC";
export const LIBRARY_CREATE_BULK = "LIBRARY_CREATE_BULK";

export const LIBRARY_DEL_REF_CODE = "LIBRARY_DEL_REF_CODE";

// LIBRARY GET USER

export const LIBRARY_GET_USER = "LIBRARY_GET_USER";

// PAGE

export const SET_MY_DOCUMENT_PAGE = "SET_MY_DOCUMENT_PAGE";
export const PREV_ROUTES_NAME = "PREV_ROUTES_NAME";
export const ORG_SERVICES = "ORG_SERVICES" 