export const API_REQUEST = "API_REQUEST";
// AUTH 
export const ACCOUNT_TYPE_OPT = "ACCOUNT_TYPE_OPT";
export const APPS_OPT = "APPS_OPT";

export const AUTH_STATUS = "AUTH_STATUS";
export const AUTH_CHECK = "AUTH_CHECK";

export const DELETEALL_COOKIES = "DELETEALL_COOKIES";

export const GOOGLE_LOGOUT = "GOOGLE_LOGOUT";
export const AUTH_GET_GOOGLE_TOKEN = "AUTH_GET_GOOGLE_TOKEN";
export const SET_USER = "SET_USER";
export const CHECK_AUTH = "CHECK_AUTH";
export const GET_DATA = "GET_DATA";

export const SIGNIN_WITH_GOOGLE = "SIGNIN_WITH_GOOGLE";
export const EX_CODE = "EX_CODE"
export const SET_USER_IF_UNAUTHENTICATED = "SET_USER_IF_UNAUTHENTICATED"
export const AUTH_SET_PASSWORD = "AUTH_SET_PASSWORD"
export const AUTH_SIGNIN = "AUTH_SIGNIN"
export const AUTH_SIGNUP = "AUTH_SIGNUP"
export const AUTH_SIGNUP_VERIFY = "AUTH_SIGNUP_VERIFY"


export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const LOGOUT = "LOGOUT";
export const AUTH_PROFILE = "AUTH_PROFILE";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_USER = "AUTH_USER";
export const AUTH_GET_USER = "AUTH_GET_USER";

export const GET_GIFT_DATA = "GET_GIFT_DATA";
export const GET_SCHEDULE_DATA = "GET_SCHEDULE_DATA";
export const GET_COUPLES_DATA = "GET_COUPLES_DATA";
export const GET_WISHES_DATA = "GET_WISHES_DATA";
export const GET_GALLERY_DATA = "GET_GALLERY_DATA";