name: Release to prod

on:
  push:
    tags:
      - "release*"   # trigger string 'release' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.name "WidodoTrh"
          git config --global user.email "widodo.rahadi00@gmail.com"

      - name: Merge main into prod
        run: |
          git fetch origin
          git checkout prod
          git merge origin/main --no-edit
          git push origin prod
